apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-database
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    labels:
      {{- include "charts.labels" . | nindent 4 }}
data:
  DATABASE_HOST: {{ .Values.mariadb.auth.host | quote }}
  DATABASE_USER: {{ .Values.mariadb.auth.username | quote }}
  DATABASE_DATABASE: {{ .Values.mariadb.auth.database | quote }}  
  DATABASE_PORT: {{ .Values.mariadb.auth.port | quote }}  