apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-database
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    labels:
      {{- include "charts.labels" . | nindent 4 }}
data:
  HOST: {{ .Values.mysql.auth.host | quote }}
  USER: {{ .Values.mysql.auth.username | quote }}
  DATABASE: {{ .Values.mysql.auth.database | quote }}  
