name: MASTER

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: jemoco/paznation-server
  EKS_CLUSTER_NAME: jemoco2
  EKS_CLUSTER_SERVICE: paznation
  APPLICATION: paznation
  ENV: production
  NODE_ENV: production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
        ref: main

    - uses: benjlevesque/short-sha@v1.2
      id: image-tag
  
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      continue-on-error: true
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      with:
        args: >
          -Dsonar.projectVersion=${{ steps.image-tag.outputs.sha }}

    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time
      timeout-minutes: 5
      continue-on-error: true
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID__CICD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY__CICD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: benjlevesque/short-sha@v1.2
        id: image-tag
  
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.image-tag.outputs.sha }}
          NODE_ENV: ${{ env.NODE_ENV }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to EKS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg NODE_ENV=${NODE_ENV} --target ${NODE_ENV} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: [build, sonar]
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID__CICD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY__CICD }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup kubeconfig
        id: setup-kubeconfig
        run: |
          aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

      - uses: benjlevesque/short-sha@v1.2
        id: image-tag

      - name: Deploy k8s yaml
        id: deploy-k8s-yaml
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.image-tag.outputs.sha }}
        run: |
          helm dependency build charts
          helm upgrade --install --wait --namespace=${{ env.APPLICATION }}-${{ env.ENV }} --create-namespace -f helm/values-${{ env.ENV }}.yaml \
          --set "nameOverride=${{ env.EKS_CLUSTER_SERVICE }}" \
          --set "image.repository=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}" \
          --set "image.tag=${{ env.IMAGE_TAG }}" \
          --set "mariadb.auth.password=${{ secrets.MYSQL_PASSWORD }}" \
          ${{ env.EKS_CLUSTER_SERVICE }} charts
          
  notification:
    runs-on: ubuntu-latest
    needs: [deploy]

    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: Build terminé
          SLACK_USERNAME: Github-bot
          SLACK_MESSAGE: 'Deploy production OK: eu-west-1'
